//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTracker.Pages
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Label lblMonthlyWorkouts;
        protected global::System.Web.UI.WebControls.Label lblMonthlyCalories;
        protected global::System.Web.UI.WebControls.Label lblMonthlyMinutes;
        protected global::System.Web.UI.WebControls.Label lblActiveGoals;
        protected global::System.Web.UI.WebControls.GridView gvRecentWorkouts;
        protected global::System.Web.UI.WebControls.GridView gvActiveGoals;
    }
}