//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTracker.Pages
{
    public partial class Goals
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtGoalType;
        protected global::System.Web.UI.WebControls.TextBox txtTargetValue;
        protected global::System.Web.UI.WebControls.TextBox txtUnit;
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtTargetDate;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentValue;
        protected global::System.Web.UI.WebControls.Button btnCreateGoal;
        protected global::System.Web.UI.WebControls.GridView gvActiveGoals;
        protected global::System.Web.UI.WebControls.GridView gvCompletedGoals;
    }
}