//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTracker.Pages
{
    public partial class LogWorkout
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlActivity;
        protected global::System.Web.UI.WebControls.TextBox txtSessionDate;
        protected global::System.Web.UI.WebControls.TextBox txtDuration;
        protected global::System.Web.UI.WebControls.TextBox txtCalories;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.Button btnLogWorkout;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl activityInfo;
        protected global::System.Web.UI.WebControls.Label lblActivityName;
        protected global::System.Web.UI.WebControls.Label lblActivityCategory;
        protected global::System.Web.UI.WebControls.Label lblCaloriesPerMinute;
    }
}