//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTracker.Pages
{
    public partial class ViewWorkouts
    {
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnClearFilter;
        protected global::System.Web.UI.WebControls.GridView gvWorkouts;
        protected global::System.Web.UI.WebControls.Label lblTotalWorkouts;
        protected global::System.Web.UI.WebControls.Label lblTotalCalories;
        protected global::System.Web.UI.WebControls.Label lblTotalMinutes;
        protected global::System.Web.UI.WebControls.Label lblAvgDuration;
    }
}